# Site settings
title: Oliver Campbell
email: ocampbell@perivan.co.uk
description: > 
  How to write an awesome site description...
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://ollyc1804.github.io" # the base hostname & protocol for your site
twitter_username: ollycampbell
github_username:  ollyc1804

# Build settings
markdown: kramdown
